version: "3.0"
services:
  orthanc:
    image: jodogne/orthanc-plugins
    container_name: orthanc
    # To be consistent with the remote Aliyun ECI deployment.
    # Aliyun uses host mode.
    hostname: medical-image-viewer
    ports:
      - 8042:8042
    volumes:
      - orthanc-db:/var/lib/orthanc/db/
      # Disable authentication
      - ../../config/orthanc.json:/etc/orthanc/orthanc.json:ro

  nginx-for-orthanc:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ../../config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8041:8041
    depends_on:
      - orthanc

  ohif-viewer:
    image: yliu120/ohif-viewer:latest
    container_name: ohif-viewer
    ports:
      - 80:80
    volumes:
      - ../../config:/usr/share/nginx/html/config
    depends_on:
      - orthanc
      - nginx-for-orthanc

volumes:
  orthanc-db: